"""initial schema

Revision ID: 1862418ef436
Revises: 
Create Date: 2026-07-31 23:39:31.781952
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.base import GUID


# revision identifiers, used by Alembic.
revision: str = '1862418ef436'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proxy', sa.String(length=512), nullable=True),
    sa.Column('warmup_day', sa.Integer(), nullable=False),
    sa.Column('session_path', sa.String(length=512), nullable=True),
    sa.Column('session_encrypted', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('messages_per_day', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('min_interval_sec', sa.Integer(), nullable=False),
    sa.Column('max_interval_sec', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', GUID(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_campaigns_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('leads',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.Column('instagram', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_leads_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('campaign_id', 'instagram', name='uq_leads_campaign_instagram')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_instagram'), ['instagram'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('metrics_daily',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_metrics_daily_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_daily')),
    sa.UniqueConstraint('campaign_id', 'day', name='uq_metrics_daily_campaign_day')
    )
    with op.batch_alter_table('metrics_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_daily_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_daily_day'), ['day'], unique=False)

    op.create_table('templates',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_templates_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('campaign_id', 'stage', name='uq_templates_campaign_stage')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campaign_id', GUID(), nullable=True),
    sa.Column('lead_id', GUID(), nullable=True),
    sa.Column('account_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('instagram_handle', sa.String(length=150), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_logs_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_logs_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_logs_lead_id_leads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('messages',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('lead_id', GUID(), nullable=False),
    sa.Column('account_id', GUID(), nullable=True),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_messages_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_messages_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_result'), ['result'], unique=False)

    op.create_table('replies',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('lead_id', GUID(), nullable=False),
    sa.Column('account_id', GUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('instagram_thread_id', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_replies_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_replies_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_replies_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replies'))
    )
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replies_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replies_lead_id'), ['lead_id'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('lead_id', GUID(), nullable=False),
    sa.Column('account_id', GUID(), nullable=True),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_scheduled_jobs_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_scheduled_jobs_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_scheduled_jobs_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_jobs'))
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_status'), ['status'], unique=False)

    op.create_table('followups',
    sa.Column('campaign_id', GUID(), nullable=False),
    sa.Column('lead_id', GUID(), nullable=False),
    sa.Column('parent_message_id', GUID(), nullable=True),
    sa.Column('stage', sa.String(length=8), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_followups_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_followups_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name=op.f('fk_followups_parent_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followups'))
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_status'))
        batch_op.drop_index(batch_op.f('ix_followups_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_followups_lead_id'))
        batch_op.drop_index(batch_op.f('ix_followups_campaign_id'))

    op.drop_table('followups')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_lead_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_account_id'))

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replies_lead_id'))
        batch_op.drop_index(batch_op.f('ix_replies_campaign_id'))

    op.drop_table('replies')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_result'))
        batch_op.drop_index(batch_op.f('ix_messages_lead_id'))
        batch_op.drop_index(batch_op.f('ix_messages_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_messages_account_id'))

    op.drop_table('messages')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_logs_result'))
        batch_op.drop_index(batch_op.f('ix_logs_lead_id'))
        batch_op.drop_index(batch_op.f('ix_logs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_logs_action'))
        batch_op.drop_index(batch_op.f('ix_logs_account_id'))

    op.drop_table('logs')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_campaign_id'))

    op.drop_table('templates')
    with op.batch_alter_table('metrics_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_daily_day'))
        batch_op.drop_index(batch_op.f('ix_metrics_daily_campaign_id'))

    op.drop_table('metrics_daily')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_instagram'))
        batch_op.drop_index(batch_op.f('ix_leads_campaign_id'))

    op.drop_table('leads')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))

    op.drop_table('campaigns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_accounts_status'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
