/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampanhasIndexRouteImport } from './routes/campanhas/index'
import { Route as CampanhasIdRouteImport } from './routes/campanhas/$id'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes/index'
import { Route as ContasIndexRouteImport } from './routes/contas/index'
import { Route as LeadsIndexRouteImport } from './routes/leads/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasIndexRoute = CampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasIdRoute = CampanhasIdRouteImport.update({
  id: '/campanhas/$id',
  path: '/campanhas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasIndexRoute = ContasIndexRouteImport.update({
  id: '/contas/',
  path: '/contas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campanhas/$id': typeof CampanhasIdRoute
  '/campanhas/': typeof CampanhasIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/contas/': typeof ContasIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campanhas/$id': typeof CampanhasIdRoute
  '/campanhas': typeof CampanhasIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/contas': typeof ContasIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campanhas/$id': typeof CampanhasIdRoute
  '/campanhas/': typeof CampanhasIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/contas/': typeof ContasIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campanhas/$id'
    | '/campanhas/'
    | '/configuracoes/'
    | '/contas/'
    | '/leads/'
    | '/logs/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campanhas/$id'
    | '/campanhas'
    | '/configuracoes'
    | '/contas'
    | '/leads'
    | '/logs'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/campanhas/$id'
    | '/campanhas/'
    | '/configuracoes/'
    | '/contas/'
    | '/leads/'
    | '/logs/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanhasIdRoute: typeof CampanhasIdRoute
  CampanhasIndexRoute: typeof CampanhasIndexRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  ContasIndexRoute: typeof ContasIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/': {
      id: '/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof CampanhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/$id': {
      id: '/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof CampanhasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas/': {
      id: '/contas/'
      path: '/contas'
      fullPath: '/contas/'
      preLoaderRoute: typeof ContasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanhasIdRoute: CampanhasIdRoute,
  CampanhasIndexRoute: CampanhasIndexRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  ContasIndexRoute: ContasIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
