"""Pacote do serviço anti-ban."""

from services.antiban.service import (
    ELIGIBLE_ACCOUNT_STATUSES,
    WARMUP_CAPS,
    RateLimitDecision,
    RoundRobinState,
    account_antiban_status,
    build_day_caps,
    check_rate_limit,
    count_consecutive_failures,
    count_successful_dms_today,
    daily_cap_for_account,
    effective_warmup_day,
    maybe_advance_warmup,
    next_account_round_robin,
    parse_proxy_urls,
    random_inter_send_delay_seconds,
    should_auto_pause,
    trigger_auto_pause,
)

__all__ = [
    "ELIGIBLE_ACCOUNT_STATUSES",
    "WARMUP_CAPS",
    "RateLimitDecision",
    "RoundRobinState",
    "account_antiban_status",
    "build_day_caps",
    "check_rate_limit",
    "count_consecutive_failures",
    "count_successful_dms_today",
    "daily_cap_for_account",
    "effective_warmup_day",
    "maybe_advance_warmup",
    "next_account_round_robin",
    "parse_proxy_urls",
    "random_inter_send_delay_seconds",
    "should_auto_pause",
    "trigger_auto_pause",
]
